version: 2

sources:
  - name: staging
    database: seventh-sensor-412710
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: nyc_green_taxi
      - name: nyc_yellow_taxi
      - name: fhv_2019
